/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "PubSub.h"

int *
join_1(IP, Port, rqstp)
	char *IP;
	int Port;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
leave_1(IP, Port, rqstp)
	char *IP;
	int Port;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
subscribe_1(IP, Port, Article, rqstp)
	char *IP;
	int Port;
	char *Article;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
unsubscribe_1(IP, Port, Article, rqstp)
	char *IP;
	int Port;
	char *Article;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
publish_1(IP, Port, Article, rqstp)
	char *IP;
	int Port;
	char *Article;
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}

int *
ping_1(rqstp)
	struct svc_req *rqstp;
{

	static int  result;

	/*
	 * insert server code here
	 */

	return(&result);
}
