/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "PubSub.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
join_1(IP, Port, clnt)
	char *IP;
	int Port;
	CLIENT *clnt;
{
	join_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.IP = IP;
	arg.Port = Port;
	if (clnt_call(clnt, join, xdr_join_1_argument, &arg, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
leave_1(IP, Port, clnt)
	char *IP;
	int Port;
	CLIENT *clnt;
{
	leave_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.IP = IP;
	arg.Port = Port;
	if (clnt_call(clnt, leave, xdr_leave_1_argument, &arg, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
subscribe_1(IP, Port, Article, clnt)
	char *IP;
	int Port;
	char *Article;
	CLIENT *clnt;
{
	subscribe_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.IP = IP;
	arg.Port = Port;
	arg.Article = Article;
	if (clnt_call(clnt, subscribe, xdr_subscribe_1_argument, &arg, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
unsubscribe_1(IP, Port, Article, clnt)
	char *IP;
	int Port;
	char *Article;
	CLIENT *clnt;
{
	unsubscribe_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.IP = IP;
	arg.Port = Port;
	arg.Article = Article;
	if (clnt_call(clnt, unsubscribe, xdr_unsubscribe_1_argument, &arg, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
publish_1(IP, Port, Article, clnt)
	char *IP;
	int Port;
	char *Article;
	CLIENT *clnt;
{
	publish_1_argument arg;
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.IP = IP;
	arg.Port = Port;
	arg.Article = Article;
	if (clnt_call(clnt, publish, xdr_publish_1_argument, &arg, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

int *
ping_1(clnt)
	CLIENT *clnt;
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ping, xdr_void, NULL, xdr_int, &clnt_res, TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	return (&clnt_res);
}
